# Generated by Django 2.2 on 2021-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0003_remove_foodmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
    ]
