# Generated by Django 2.2 on 2021-03-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0004_foodmodel_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetFoodModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Có người', 1), ('Trống', 2), ('Tạm ngưng hoạt động', 3)], default='Trống', max_length=255)),
                ('person', models.IntegerField()),
            ],
        ),
    ]
