# Generated by Django 2.2 on 2021-03-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0005_getfoodmodel_tablemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='status',
            field=models.CharField(choices=[('Có người', 'Có người'), ('Trống', 'Trống'), ('Tạm ngưng hoạt động', 'Tạm ngưng hoạt động')], default='Trống', max_length=255),
        ),
        migrations.CreateModel(
            name='BookTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_book', models.DateTimeField(auto_now=True)),
                ('name_book', models.CharField(max_length=255)),
                ('phone_book', models.CharField(max_length=15)),
                ('number_of_people', models.IntegerField()),
                ('money_book', models.DecimalField(decimal_places=2, max_digits=19)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.TableModel')),
            ],
        ),
    ]
