# Generated by Django 2.2 on 2021-03-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20210319_0823'),
        ('food_table_manager', '0006_auto_20210319_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='food_price',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='getfoodmodel',
            name='food_price',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.CreateModel(
            name='DetailFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_material', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.FoodModel')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialModel')),
            ],
        ),
    ]
