# Generated by Django 2.2 on 2021-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0007_auto_20210322_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='getDetailFoodModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('amount_material', models.IntegerField(default=1)),
            ],
        ),
    ]
