# Generated by Django 2.2 on 2021-03-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0008_getdetailfoodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdetailfoodmodel',
            name='food',
            field=models.IntegerField(default=0),
        ),
    ]
