# Generated by Django 2.2 on 2021-03-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0009_getdetailfoodmodel_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getdetailfoodmodel',
            name='food',
        ),
    ]
