# Generated by Django 2.2 on 2021-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0010_remove_getdetailfoodmodel_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='person',
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booktablemodel',
            name='time_book',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='status',
            field=models.CharField(choices=[('Có người', 'Có người'), ('Trống', 'Trống'), ('Tạm ngưng hoạt động', 'Tạm ngưng hoạt động'), ('Bàn đã đặt', 'Bàn đã đặt')], default='Trống', max_length=255),
        ),
    ]
