# Generated by Django 2.2 on 2021-03-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0012_auto_20210324_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktablemodel',
            name='money_book',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_price',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='getfoodmodel',
            name='food_price',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
