# Generated by Django 2.2 on 2021-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0013_auto_20210327_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktablemodel',
            name='money_book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='getfoodmodel',
            name='food_price',
            field=models.IntegerField(),
        ),
    ]
