# Generated by Django 3.1.7 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0014_auto_20210330_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='getfoodmodel',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detailfoodmodel',
            name='amount_material',
            field=models.IntegerField(),
        ),
    ]
