# Generated by Django 3.1.7 on 2021-04-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0015_auto_20210413_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getfoodmodel',
            old_name='amount',
            new_name='food_amount',
        ),
    ]
