# Generated by Django 2.2 on 2021-03-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0009_auto_20210324_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_loss', models.IntegerField()),
                ('time', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialModel')),
            ],
        ),
    ]
