# Generated by Django 2.2 on 2021-03-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20210324_1404'),
        ('comsum', '0002_getlossmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveConsumption',
            fields=[
                ('material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum_material', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_reality', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialModel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_consumption', models.IntegerField()),
                ('time_consumption', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialModel')),
            ],
        ),
    ]
