# Generated by Django 3.1.7 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comsum', '0007_auto_20210330_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartProduct',
            fields=[
                ('total', models.IntegerField()),
                ('month', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DateOfWare',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='getConsumptionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255)),
                ('amount_consumption', models.IntegerField()),
                ('time_consumption', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GetWareHouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('material_reality', models.IntegerField()),
            ],
        ),
    ]
