# Generated by Django 2.2 on 2021-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20210317_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetImportMaterialModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('import_date', models.DateTimeField()),
            ],
        ),
    ]
