# Generated by Django 2.2 on 2021-03-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_getimportmaterialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmaterialmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
