# Generated by Django 2.2 on 2021-03-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20210319_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmaterialmodel',
            name='import_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
