# Generated by Django 2.2 on 2021-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20210327_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimportmaterialmodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='importmaterialmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
