# Generated by Django 3.1.7 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_auto_20210330_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='getSum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
