# Generated by Django 2.2 on 2021-03-24 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_table_manager', '0011_auto_20210323_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=255)),
                ('phone_customer', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.TableModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
