# Generated by Django 2.2 on 2021-03-26 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_table_manager', '0012_auto_20210324_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(default='', max_length=255)),
                ('phone_customer', models.CharField(default='', max_length=255)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.TableModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseListBill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintBill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField()),
                ('food_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SumMoneyBill',
            fields=[
                ('sum', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetailBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=19)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.BillModel')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.FoodModel')),
            ],
        ),
    ]
