# Generated by Django 2.2 on 2021-03-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_table_manager', '0011_auto_20210323_1355'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmodel',
            name='name_customer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='phone_customer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DetailBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=19)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.BillModel')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_table_manager.FoodModel')),
            ],
        ),
    ]
