# Generated by Django 2.2 on 2021-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210324_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailbillmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
