# Generated by Django 2.2 on 2021-03-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210324_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoneybill',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailbillmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='summoneybill',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
