# Generated by Django 2.2 on 2021-03-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210327_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoneybill',
            name='sum',
        ),
        migrations.AddField(
            model_name='summoneybill',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
