# Generated by Django 2.2 on 2021-03-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210327_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoneybill',
            old_name='id',
            new_name='id_sum',
        ),
    ]
