# Generated by Django 3.1.7 on 2021-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210330_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillId',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField()),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GetAmount',
            fields=[
                ('amount', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetBillId',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetBillInfo',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GetCount',
            fields=[
                ('count', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetDem',
            fields=[
                ('dem', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetFoodId',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetFoodOrdered',
            fields=[
                ('food_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('food_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='getPriceFood',
            fields=[
                ('food_price', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SumMoney',
            fields=[
                ('sum_price', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
